{% set version = "6.3.0" %}

package:
  name: qwt
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/qwt/files/qwt/{{ version }}/qwt-{{ version }}.tar.bz2
  sha256: dcb085896c28aaec5518cbc08c0ee2b4e60ada7ac929d82639f6189851a6129a
  patches:
    # Can't seem to avoid /usr/local/ install without patch
    - qwtconfig.pri.patch
    # build in release mode
    - windows.patch
    # Fix issues with conda environments and finding gl.h
    - 0001-Added-include-path-for-conda-env.patch

build:
  number: 1
  skip: true  # [ppc64le]
  run_exports:
    - {{ pin_subpackage('qwt', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - make                               # [unix]
    - libgl-devel                        # [linux]
  host:
    - libgl-devel                        # [linux]
    - qt6-main
  run:
    - qt6-main

test:
  commands:
    - test -f ${PREFIX}/lib/libqwt${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\include\\qwt.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\qwt.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\qwt.lib exit 1  # [win]

about:
  home: http://qwt.sourceforge.net/
  license: Qwt, Version 1.0
  license_file: COPYING
  summary: Qt widgets for technical applications
  doc_url: http://qwt.sourceforge.net/
  dev_url: https://sourceforge.net/projects/qwt/

extra:
  recipe-maintainers:
    - traversaro
    - ceholden
    - jschueller
    - marcelotrevisani
