{% set version = "6.1.6" %}

package:
  name: qwt
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/qwt/files/qwt/{{ version }}/qwt-{{ version }}.tar.bz2
  sha256: 99460d31c115ee4117b0175d885f47c2c590d784206f09815dc058fbe5ede1f6
  patches:
    # Can't seem to avoid /usr/local/ install without patch
    - qwtconfig.pri.patch
    # build in release mode
    - windows.patch

build:
  skip: true  # [win and vc<14]
  number: 0
  merge_build_host: true  # [linux]
  run_exports:
    - {{ pin_subpackage('qwt', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxrandr') }}             # [linux]
    - {{ cdt('alsa-lib') }}              # [linux]
    - {{ cdt('xorg-x11-server-xvfb') }}  # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('expat-devel') }}           # [linux]
    - {{ cdt('pcre') }}                  # [linux and cdt_name != 'cos6']
    - make                               # [unix]
  host:
    - qt
  run:
    - qt

test:
  commands:
    - test -f ${PREFIX}/lib/libqwt${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\include\\qwt.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\qwt.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\qwt.lib exit 1  # [win]

about:
  home: http://qwt.sourceforge.net/
  license: Qwt, Version 1.0
  license_file: COPYING
  summary: Qt widgets for technical applications
  doc_url: http://qwt.sourceforge.net/
  dev_url: https://sourceforge.net/projects/qwt/

extra:
  recipe-maintainers:
    - ceholden
    - jschueller
    - marcelotrevisani
